require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'weightress' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

# NOTE: Do not remove, needed to keep WatermelonDB compiling:
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true


  target 'weightressTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 
  # use_flipper!
  # use_flipper!({ 'Flipper' => '0.74.0' })

  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'weightress-tvOS' do
  # Pods for weightress-tvOS

  target 'weightress-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
